### ISSUE TITLE
RTL layout error.

### ISSUE THREAD

**Issue by Saifallak** [phpsa/filament-password-reveal#14]
# in RTL the eye icon is aligned to the wrong side.

![image](https://user-images.githubusercontent.com/6053156/229841543-df850242-7231-4bfd-80ab-ff2838951989.png)

**Comment by mstfkhazaal** [comment]
@Saifallak Did you find a solution?

**Comment by phpsa** [comment]
Will open an PR from our end

**Comment by mstfkhazaal** [comment]
@phpsa 
I found a bug in the padding space, I tried a lot to fix it, but I didn't succeed because I don't have enough alpine experience

![image](https://user-images.githubusercontent.com/47450090/231096491-78b9cae9-577b-48c5-937f-5f9b37498443.png)

**Comment by mstfkhazaal** [comment]
@phpsa any update?

**Comment by phpsa** [comment]
@mstfkhazaal - sorry will look into this shorlty

**Comment by mstfkhazaal** [comment]
> @mstfkhazaal - sorry will look into this shorlty

Well, I'm waiting
