### ISSUE TITLE
How to use the Filament Password Reveal plugin in my Filament PHP project?

### ISSUE THREAD

**Issue by gabri231** [phpsa/filament-password-reveal#15]
Hi there,

I'm trying to use the `phpsa/filament-password-reveal` plugin in my Filament PHP project, but I'm not sure how to get it working. I've installed the package using Composer, but I'm not sure how to enable the password reveal feature in my forms.

Could you provide some guidance on how to set up the plugin?

Any help or guidance you can provide would be greatly appreciated!

Thanks in advance for your help.

**Comment by phpsa** [comment]
HI,

Make sure to import the component and use it the same as the filament textinput,

`Password::make('password')->autocomplete('new_password')`

the documentation needed is in the readme

**Comment by GabrielCalleDev** [comment]
Thanks, the problem was that I was loading the wrong library.

In this case it works for me with:

```php
use Phpsa\FilamentPasswordReveal\Password;
```

Thanks! :)
